name: Build and push Docker image (amd64, arm64) to ghcr.io

on:
  workflow_dispatch: # allow manual trigger
  push:
    branches:
      - "main"
    paths-ignore:
      - ".gitignore"
      - "README.md"
      # - ".github/**"
  pull_request:
    branches: [ "main" ] # only PRs against main

# permissions:
#   contents: read
#   packages: write

jobs:
  docker:
    # permissions:
    #   contents: read # for actions/checkout to fetch code
    #   security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    #   actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64 # ,linux/arm/v7
          push: true
          tags: |
            ghcr.io/bitflow/license-scan-export:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
